# Dependencies
# markdown:         redcarpet
# redcarpet:
# extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
# highlighter:      pygments
# highlighter:      rouge

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Permalinks
permalink:        pretty

# Setup
# title:            TJ CompSci
# tagline:          'All things CS @ TJHSST'
# description:      'All things CS @ TJHSST'
# url:              http://tjcompsci.github.io
# baseurl:          /

title:            Jongjin Kim
tagline:          'Educational Psychology | Educational Neuroscience @ UA'
description:      'Educational Psychology | Educational Neuroscience @ UA'
url:              http://jkim205.github.io
baseurl:          /


#
# author:
#   name:           'Ria Galanos'
#   url:            https://twitter.com/cscheerleader

author:
  name:           'Jongjin Kim'
  url:            https://jkim.people.ua.edu


plugins: 		 

- jekyll-paginate 
- jekyll-gist


include: ["_pages"]

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde


